// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSfZPykwUqhEdYSg5i-FYIy-Af2rPVwc',
    appId: '1:567456527632:web:a2eef9508c5307e9f62195',
    messagingSenderId: '567456527632',
    projectId: 'food-app-92caa',
    authDomain: 'food-app-92caa.firebaseapp.com',
    storageBucket: 'food-app-92caa.appspot.com',
    measurementId: 'G-3KS0KTXXQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIlZQtFp0NMgHUFn4nWq54hUEkCuqGcM',
    appId: '1:567456527632:android:107f8479d27f704df62195',
    messagingSenderId: '567456527632',
    projectId: 'food-app-92caa',
    storageBucket: 'food-app-92caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHsWdzR2cYFjk0m60PNX0IdkP16Ye2ws',
    appId: '1:567456527632:ios:77227bc1af8ba24ff62195',
    messagingSenderId: '567456527632',
    projectId: 'food-app-92caa',
    storageBucket: 'food-app-92caa.appspot.com',
    iosBundleId: 'com.example.foodApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqHsWdzR2cYFjk0m60PNX0IdkP16Ye2ws',
    appId: '1:567456527632:ios:77227bc1af8ba24ff62195',
    messagingSenderId: '567456527632',
    projectId: 'food-app-92caa',
    storageBucket: 'food-app-92caa.appspot.com',
    iosBundleId: 'com.example.foodApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSfZPykwUqhEdYSg5i-FYIy-Af2rPVwc',
    appId: '1:567456527632:web:b54b322b1b66de5ff62195',
    messagingSenderId: '567456527632',
    projectId: 'food-app-92caa',
    authDomain: 'food-app-92caa.firebaseapp.com',
    storageBucket: 'food-app-92caa.appspot.com',
    measurementId: 'G-0VENWX870K',
  );
}
